# - name: "Install and start nginx"
#   hosts: frontend
#   become: yes
#   tasks: 
#   - name: install nginx
#     ansible.builtin.package:
#       name: nginx
#       state: present

#   - name: start nginx
#     ansible.builtin.service:
#       name: nginx
#       state: started
#       enabled: yes 




# - name: INstall and start nginx
#   hosts: frontend
#   become: yes
#   tasks:
#   - name : Install nginx
#     ansible.builtin.package:
#       name: nginx
#       state: present

#   - name: Start nginx
#     ansible.builtin.service:
#       name: nginx
#       enabled: yes 


- name: Install and start nginx
  hosts: frontend
  become: yes
  tasks:


  - name: Stop nginx
    ansible.builtin.service:
      name: nginx
      state: stopped
      enabled: no 

    - name: Uninstall nginx
    ansible.builtin.package:
      state: absent    
